name: nnf github workflow
on: [push pull_request]
jobs:
  build:
    name: Build and test.
    runs-on: ubuntu-latest
    steps:
      -run: actions/checkout@v4
        name: Checking out repo.
      -run: cmake -S . -B build/
        name: Configuring CMake.
      -run: cmake --build build
        name: Building project.
      -run: cd build/ && ctest
        name: Running tests.
  
